#! /nix/store/rlq03x4cwf8zn73hxaxnx0zn5q9kifls-bash-5.3p3/bin/bash -e
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/b8w6xj2isq4m120sz2gg4hb5gxhjmzca-chromium-143.0.7499.40/bin'':'/':'}
PATH='/nix/store/b8w6xj2isq4m120sz2gg4hb5gxhjmzca-chromium-143.0.7499.40/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/nkr2xvaixc94b4fwf59gmjrll6728qx8-wtype-0.4/bin'':'/':'}
PATH='/nix/store/nkr2xvaixc94b4fwf59gmjrll6728qx8-wtype-0.4/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/zvz16r8szmxhpvl36fs3b4izbcr4swmm-libnotify-0.8.7/bin'':'/':'}
PATH='/nix/store/zvz16r8szmxhpvl36fs3b4izbcr4swmm-libnotify-0.8.7/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/4rg4l7wlxaxmfihv83a112bdshdk34cs-foot-1.25.0/bin'':'/':'}
PATH='/nix/store/4rg4l7wlxaxmfihv83a112bdshdk34cs-foot-1.25.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/kw3rlz6a48c3hi03hjv5xjw26304lsx2-alacritty-0.16.1/bin'':'/':'}
PATH='/nix/store/kw3rlz6a48c3hi03hjv5xjw26304lsx2-alacritty-0.16.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/x3zjxxz8m4ki88axp0gn8q8m6bldybba-gnugrep-3.12/bin'':'/':'}
PATH='/nix/store/x3zjxxz8m4ki88axp0gn8q8m6bldybba-gnugrep-3.12/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/drc7kang929jaza6cy9zdx10s4gw1z5p-gnused-4.9/bin'':'/':'}
PATH='/nix/store/drc7kang929jaza6cy9zdx10s4gw1z5p-gnused-4.9/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/imad8dvhp77h0pjbckp6wvmnyhp8dpgg-coreutils-9.8/bin'':'/':'}
PATH='/nix/store/imad8dvhp77h0pjbckp6wvmnyhp8dpgg-coreutils-9.8/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/av4xw9f56xlx5pgv862wabfif6m1yc0a-findutils-4.10.0/bin'':'/':'}
PATH='/nix/store/av4xw9f56xlx5pgv862wabfif6m1yc0a-findutils-4.10.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/b8kv3bslizrpsk3h079zhlnsvnlb27ww-blueman-2.4.6/bin'':'/':'}
PATH='/nix/store/b8kv3bslizrpsk3h079zhlnsvnlb27ww-blueman-2.4.6/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/pzr8vq62a20cc3xcsllmsbsrvmf8yapq-pavucontrol-6.2/bin'':'/':'}
PATH='/nix/store/pzr8vq62a20cc3xcsllmsbsrvmf8yapq-pavucontrol-6.2/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/3jk8py96bwnn0sgl1r0dwr0vif4cvivw-wireplumber-0.5.12/bin'':'/':'}
PATH='/nix/store/3jk8py96bwnn0sgl1r0dwr0vif4cvivw-wireplumber-0.5.12/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/334afxah19b3hr6ll93pfxlcyhhh2vws-pipewire-1.4.9/bin'':'/':'}
PATH='/nix/store/334afxah19b3hr6ll93pfxlcyhhh2vws-pipewire-1.4.9/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/7k1awkdb4s3xdg13vqw782wm4pkdj4dl-network-manager-applet-1.36.0/bin'':'/':'}
PATH='/nix/store/7k1awkdb4s3xdg13vqw782wm4pkdj4dl-network-manager-applet-1.36.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/h91szsp5bk28zddrdp3y0bpl7nx9pkj4-networkmanager-1.54.1/bin'':'/':'}
PATH='/nix/store/h91szsp5bk28zddrdp3y0bpl7nx9pkj4-networkmanager-1.54.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/swv4134cdjmxjs117nd9imv1zia4sh5p-thunar-archive-plugin-0.6.0/bin'':'/':'}
PATH='/nix/store/swv4134cdjmxjs117nd9imv1zia4sh5p-thunar-archive-plugin-0.6.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/5hl8jphipmaqw60178d0yklpwlllh1qb-thunar-volman-4.20.0/bin'':'/':'}
PATH='/nix/store/5hl8jphipmaqw60178d0yklpwlllh1qb-thunar-volman-4.20.0/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/cig8wpyn2c4q83vj7y8hsbj666b1m6fw-thunar-4.20.6/bin'':'/':'}
PATH='/nix/store/cig8wpyn2c4q83vj7y8hsbj666b1m6fw-thunar-4.20.6/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/13d432s7zrxh43s8nrvxw2jq4sww4k3x-xdg-utils-1.2.1/bin'':'/':'}
PATH='/nix/store/13d432s7zrxh43s8nrvxw2jq4sww4k3x-xdg-utils-1.2.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/11s4w7n8qq1mm0jahhxp00kzwvh18xa3-brightnessctl-0.5.1/bin'':'/':'}
PATH='/nix/store/11s4w7n8qq1mm0jahhxp00kzwvh18xa3-brightnessctl-0.5.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
PATH=${PATH/':''/nix/store/jklwza6sjb4n5lygaj601hzvl5zfzrz0-swaybg-1.2.1/bin'':'/':'}
PATH='/nix/store/jklwza6sjb4n5lygaj601hzvl5zfzrz0-swaybg-1.2.1/bin'$PATH
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS/':''/nix/store/fms1sm9hb1apzmv3kiwyz5nqq1v721ry-shared-mime-info-2.4/share'':'/':'}
XDG_DATA_DIRS='/nix/store/fms1sm9hb1apzmv3kiwyz5nqq1v721ry-shared-mime-info-2.4/share'$XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
export XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS/':''/nix/store/0ciz2xdaml8zjgah41bq29w6mzl8rlns-hicolor-icon-theme-0.18/share'':'/':'}
XDG_DATA_DIRS='/nix/store/0ciz2xdaml8zjgah41bq29w6mzl8rlns-hicolor-icon-theme-0.18/share'$XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
export XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS/':''/nix/store/686s7bl7da7rh1vmcq9x3k9sfb2kzqkg-adwaita-icon-theme-49.0/share'':'/':'}
XDG_DATA_DIRS='/nix/store/686s7bl7da7rh1vmcq9x3k9sfb2kzqkg-adwaita-icon-theme-49.0/share'$XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
export XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS:+':'$XDG_DATA_DIRS':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS/':''/nix/store/rgnmhjk5xzlazwr6b79shm5619s1i3m2-papirus-icon-theme-20250501/share'':'/':'}
XDG_DATA_DIRS='/nix/store/rgnmhjk5xzlazwr6b79shm5619s1i3m2-papirus-icon-theme-20250501/share'$XDG_DATA_DIRS
XDG_DATA_DIRS=${XDG_DATA_DIRS#':'}
XDG_DATA_DIRS=${XDG_DATA_DIRS%':'}
export XDG_DATA_DIRS
exec -a "$0" "/nix/store/y40mi1c1jqp5z05lrdj5a1s8xbqmxm1a-nixlytile-git/bin/.nixlytile-wrapped"  "$@" 
